services:
  server:
    build: ./server
    container_name: vyom-server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server/uploads:/app/uploads
    restart: always

  client:
    build: ./vyom-club
    container_name: vyom-client
    ports:
      - "5173:80"
    depends_on:
      - server
    restart: always
